### ISSUE TITLE
Not working on Xcode Cloud.

### ISSUE THREAD

**Issue by noppefoxwolf** [maiyama18/LicensesPlugin#7] opened 2023-03-06 17:33 UTC
<img width="1454" alt="CleanShot 2023-03-07 at 02 32 02@2x" src="https://user-images.githubusercontent.com/2066707/223186563-d4efb3c8-2536-428a-a4bc-83b7b6cfe686.png">

**Comment by noppefoxwolf** [comment] 2023-03-06 17:38
In local case, I accepted a dialog that looks like following image.
I need to accept dialog without GUI when running in Xcode Cloud.

<img width="361" alt="200274173-e3e1e1f7-9d93-4a5e-ac4e-062e6cbc5200" src="https://user-images.githubusercontent.com/2066707/223187452-ce3250d8-024d-4334-979c-7aef8397d97f.png">

**Comment by maiyama18** [comment] 2023-03-07 00:41
@noppefoxwolf  Thanks for reporting the issue! Did you try skipping plugin validations by executing below in scripts?

```
defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
```

Refs: 

- https://zenn.dev/kyome/articles/56974297795cb5
- https://developer.apple.com/documentation/xcode/writing-custom-build-scripts

**Comment by noppefoxwolf** [comment] 2023-03-07 03:14
@maiyama18 Thanks. It's working after I put the script.
But plugin cannot write to file which haven't permission.

<img width="1411" alt="CleanShot 2023-03-07 at 12 11 18@2x" src="https://user-images.githubusercontent.com/2066707/223311247-35028916-1907-4bce-b77d-a64371595b9e.png">

**Comment by maiyama18** [comment] 2023-03-07 03:44
@noppefoxwolf Thanks! 
I can't figure out the cause of that error right now, so I'll investigate by making a sample project and try it out on xcode cloud later. The current implementation of this plugin is very naive, and may cause some kind of problem like that.

**Comment by noppefoxwolf** [comment] 2023-03-07 03:49
@maiyama18 I made PR #8 that resolve permission issues.
It's working fine in my local and cloud environments.
Please try it.

**Comment by maiyama18** [comment] 2023-03-07 03:53
🆒 
Thank you so much! I'll try it later.

**Comment by maiyama18** [comment] 2023-03-07 12:45
Fixed by https://github.com/maiyama18/LicensesPlugin/pull/8

**Closed as completed by maiyama18** 2023-03-07 12:45 UTC
